### PR TITLE
Update to analyzer 1.5.0, migrate from deprecated AnalysisSession.getParsedUnit()

### PR DESCRIPTION
**Pull request by scheglov**

### CODE REVIEW

**Comment by scheglov** [comment]
There are failing tests, but I'm surprised that my changes caused them, e.g. `SocketException: Failed host lookup: 'arg.com'`. Are there pre-existing failures in testing, or can you think of a way my changes affected it?

**Comment by natebosch** [comment]
@jonasfj @sigurdm - do you have background on the failing tests?

**Comment by natebosch** [comment]
This does look like it's failing on master too so I think it's probably safe to land with a failing CI, but I'll defer to @jonasfj for that decision.

**Comment by scheglov** [comment]
It seems that the tests are green now.

**Review by jonasfj — APPROVED** [review]

**Pull request merged**
