### PR TITLE
Change terminology for precompilation to building

### PR DESCRIPTION
**Pull request by mit-mit**
Fixes https://github.com/dart-lang/pub/issues/2951

### CODE REVIEW

**Comment by mit-mit** [comment]
I'm puzzled about the remaining test failures, like:
https://github.com/dart-lang/pub/runs/2677300307

**Comment by jonasfj** [comment]
I'll take a look at the test failure... probably it has to do with our partial migration of `pub` code...

**Review by jonasfj — APPROVED** [review]
I'll fix tests and merge.

**Comment by jonasfj** [comment]
Merged as part of https://github.com/dart-lang/pub/pull/3017

**Pull request closed without merging**
