### PR TITLE
fix: False detection of non-ignored files with non-ascii unicode characters

### PR DESCRIPTION
**Pull request by Gustl22**
- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Comment by Gustl22** [comment]
Currently we cannot publish with the new dart version, as it does not allow special characters to be in the file name.
See: https://github.com/Gustl22/audioplayers/actions/runs/8031208161/job/21939294316#step:4:873

**Comment by sigurdm** [comment]
Could you run `dart format`?

**Comment by Gustl22** [comment]
Sure :)

**Comment by sigurdm** [comment]
NP. 

We could also consider passing `-z` instead to get the raw strings out... not sure if it is better or worse than this.

**Comment by Gustl22** [comment]
`git -c core.quotePath=false ls-files --cached --exclude-standard --recurse-submodules ` gives:
```bash
CHANGELOG.md
LICENSE
README.md
lib/test_pkg.dart
coins_non_ascii_и.wav
pubspec.yaml
```

`git ls-files -z --cached --exclude-standard --recurse-submodules` gives:
```bash
CHANGELOG.mdLICENSEREADME.mdlib/test_pkg.dartcoins_non_ascii_и.wavpubspec.yaml
```

But for some reason in the test process with `-c core.quotePath=false` option, it is returned as:
```
CHANGELOG.md
LICENSE
README.md
lib/test_pkg.dart
non_ascii_Ð¸.txt
pubspec.yaml
```

**Comment by Gustl22** [comment]
> then forward it to https://api.dart.dev/stable/3.3.0/dart-io/Process/run.html

Thank you @sigurdm, that was actually it. Normally it would work without a specifying the encoding, but on Windows `SystemEncoding` is defaulted by "the currently active code page".
Unfortunately I had to rework the `_doProcess` function, because `Process.start` doesn't match with the parameters of `Process.run`, obviously because of the `stdoutEncoding` param.

**Comment by sigurdm** [comment]
Thanks for the contribution!

> Currently we cannot publish with the new dart version,

FWIW there is a `--skip-validation` option to `dart pub publish` to work around bugs like this.

**Review by sigurdm — APPROVED** [review]

**Pull request merged**
