### PR TITLE
Fix null-safety warning in dart.dart

### PR DESCRIPTION
**Pull request by dcharkes**
Fixes

* https://github.com/dart-lang/pub/issues/3513

### CODE REVIEW

**Comment by sigurdm** [comment]
I think this change has not yet been published in pub.dev: https://github.com/dart-lang/webdev/commit/ab82887641d794d00d7d510e4f3d005c491adce3#diff-99089b7762498f852485fbc2c7a85c455ba0a793f3756715f47e50ce05ae1ef3L133


cc @jakemac53

**Comment by sigurdm** [comment]
I don't think we can land this until the update of webdev has been published.

**Comment by jakemac53** [comment]
I can work on publishing that

**Comment by sigurdm** [comment]
Now test_core is holding us back. It also depends on frontend_server_client: ^2.1.0

**Review by sigurdm — APPROVED** [review]
LGTM

**Comment by dcharkes** [comment]
Thanks @sigurdm!

**Comment by sigurdm** [comment]
Hmm seems this is breaking google3 - we probably also need a roll there...
https://fusion2.corp.google.com/invocations/7ebe1e59-a883-4656-bbde-f75160def304/targets/%2F%2Fdart%2Fsdk%2Frapture:dartsdk_deb_test/log

**Pull request merged**
