### PR TITLE
Allow third-party tools to resolve dependencies

### PR DESCRIPTION
**Pull request by blaugold**
Tools like [melos](https://github.com/invertase/melos) need to be able to resolve dependencies, to link up local packages for development. 

With this change, up-to-date checks of `package_config.json`, `.packages` and `pubspec.lock` are skipped if `package_config.json` has been generated by a tool other than `pub`. This behavior is limited to `pub run` and `dart run`. `pub get` does the normal checks and overrides third-party modifications.

This change also eliminates an [unnecessary call](https://github.com/dart-lang/pub/blob/0035a40f25d027130c0314571da53ffafc6d973b/lib/src/executable.dart#L97) of `Entrypoint.assertUpToDate`. Just a few lines above, `Entrypoint.resolveExecutable` is called, which calls `assertUpToDate` in the process.

### CODE REVIEW

**Comment by jonasfj** [comment]
Hmm, should we consider solving this problem by adding first class support for local dependency overrides with something like a `pubspec-overrides.yaml` sitting next to `pubspec.yaml`.

Maybe, this isn't a problem in reality, but if we encourage third-party tools to generate `package-config.json`, might we not risk that adding new features, build steps, etc. to `dart pub get` will be harder in the future.

-------

On the flip side: we could also simplify our logic and only check the generator when timestamps don't align.

**Comment by jonasfj** [comment]
For the record, I'm not principally opposed to this change, just considering/brainstorming possible future implications :)

**Comment by blaugold** [comment]
I think your right @jonasfj, that a cleaner, more universal approach is to support something like `pubspec-overrides.yaml`.
In issue #2161, a few possible solutions have been discussed, and it seems to me that a `pubspec-overrides.yaml` file provides the best trade-off between usability and flexibility. Users can write them manually, or have a tool generate them and still see what the current configuration is. It also works well with other tools running `pub get` for the user, such as flutter and IDE extensions.

Currently, melos is working around `pub` not having something like `pubspec-overrides.yaml`. It recreates the workspace with all of its packages in a temporary directory, but with only the files required to run `pub get`. It then calculates the required `dependency-overrides`, modifies the `pubspec.yaml` files and runs `pub get` in the temporary directory. The last step is to copy some of the files `pub` generated (e.g. `package_config.json`), back to the actual packages.

**Comment by blaugold** [comment]
Following up on my last comment, I'm closing this PR since it's an attempt to enable a solution which is already a workaround.

**Comment by sigurdm** [comment]
In any case - thanks for the contribution. I think it highlights an area where we need to find a better solution!

**Comment by Salakar** [comment]
I would note there are places (at least in Flutter tooling) where 'third-party tool detection and doing something different' is already a thing, e.g. https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/dart/pub_get_test.dart#L49

I'm not against having a `pubspec-overrides.yaml` file but my initial thoughts are that this sounds like a user editable file that is VCS tracked - having tools edit/generate into it could be problematic - especially where the file already exists in a project. I'd personally rather avoid having Melos modify user editable & CCS tracked files 😅

**Pull request closed without merging**
