### PR TITLE
Use latest CI Dart setup

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Wonder why this is failing now...

**Comment by natebosch** [comment]
```
Could not find a file named "pubspec.yaml" in "C:\Users\runneradmin\.pub-cache\hosted\pub.dartlang.org\_fe_analyzer_shared-21.0.0".
```

how did this end up trying to run tests in the pub cache?

**Comment by kevmoo** [comment]
> ```
> Could not find a file named "pubspec.yaml" in "C:\Users\runneradmin\.pub-cache\hosted\pub.dartlang.org\_fe_analyzer_shared-21.0.0".
> ```
> 
> how did this end up trying to run tests in the pub cache?

🤷  – smells like a bug. Weird to have it show up with this CI change, though.

**Comment by jonasfj** [comment]
> how did this end up trying to run tests in the pub cache?

Did it... I think that `dart test` has a check that dependencies are installed, and this check failed.. How I don't know... we seem to run `dart pub upgrade` in a previous step, and it seems to be using the correct `PUB_CACHE`.

**Comment by kevmoo** [comment]
Should I close this out? Thoughts?

**Comment by kevmoo** [comment]
I'd love to know why this is failing...

**Comment by natebosch** [comment]
@googlebot I consent.

**Comment by natebosch** [comment]
One difference that could be interesting in the diff between `0.1` and `1.0` - we didn't used to set a `PUB_CACHE` environment variable and now we do...

https://github.com/dart-lang/setup-dart/compare/v0.1...v1.0#diff-4209d788ad32c40cbda3c66b3de47eefb929308ca703bb77a6382625986add17R63

**Comment by natebosch** [comment]
@kevmoo - do you know if we have any successful uses of `setup-dart@v1.0` running on windows?

**Comment by natebosch** [comment]
There is definitely something strange going on with paths here.

We have 2 different representations for the paths. Some paths look like `D:\a\pub\pub/.dart_tool/pub.dart.snapshot.dart2` while others look like `/c/Users/runneradmin/.pub-cache` which should correspond to `C:/Users/runneradmin/.pub-cache`. In the `.package_config.json` file we end up mixing those inappropriately to end up with things like:

 `"rootUri": "file:///D:/c/Users/runneradmin/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-23.0.0"`
 
 which should be:
 
 `"rootUri": "file:///C:/Users/runneradmin/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-23.0.0"`

**Comment by jakemac53** [comment]
I tried sending https://github.com/dart-lang/setup-dart/pull/38 but things do seem to generally work there. Not sure what the difference is with this repo, although maybe it isn't a coincidence that this is happening in the pub repo?

**Comment by kevmoo** [comment]
Doesn't pkg:build and friends run bots on Windows?

**Comment by mit-mit** [comment]
Replaced by https://github.com/dart-lang/pub/pull/3054

**Pull request closed without merging**
