### PR TITLE
Promote `pub upgrade` in `pub outdated`

### PR DESCRIPTION
**Pull request by mit-mit**
Draft implementation, tests not updated yet.

WDYT @sigurdm @jonasfj

### CODE REVIEW

**Comment by mit-mit** [comment]
Sample output for regular outdated (without null safety mode):

```
$ dart pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name  Current  Upgradable  Resolvable  Latest

direct dependencies:
path          *1.6.2   *1.6.2      1.7.0       1.7.0

dev_dependencies: all up-to-date.

1 dependency is constrained to a version that is older than a resolvable version.
To update it, edit pubspec.yaml.


$ ~/tmp/pub.exe outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name  Current  Upgradable  Resolvable  Latest

direct dependencies:
path          *1.6.2   *1.6.2      1.7.0       1.7.0

dev_dependencies: all up-to-date.

1 dependency is constrained to a version that is older than a resolvable version.
To update it, edit pubspec.yaml, or run `dart pub upgrade --major-versions`.

```

**Comment by mit-mit** [comment]
Sample output with null safety mode:

```
$ dart pub outdated --mode=null-safety
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name  Current  Upgradable  Resolvable            Latest

direct dependencies:
path          ✗1.7.0   ✗1.7.0      ✓1.8.0-nullsafety.3   ✓1.8.0-nullsafety.3

dev_dependencies:
pedantic      ✗1.9.2   ✗1.9.2      ✓1.10.0-nullsafety.3  ✓1.10.0-nullsafety.3

2  dependencies are constrained to versions that are older than a resolvable version.
To update these dependencies, edit pubspec.yaml.


$ ~/tmp/pub.exe outdated --mode=null-safety
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name  Current  Upgradable  Resolvable            Latest

direct dependencies:
path          ✗1.7.0   ✗1.7.0      ✓1.8.0-nullsafety.3   ✓1.8.0-nullsafety.3

dev_dependencies:
pedantic      ✗1.9.2   ✗1.9.2      ✓1.10.0-nullsafety.3  ✓1.10.0-nullsafety.3

2  dependencies are constrained to versions that are older than a resolvable version.
To update these dependencies, edit pubspec.yaml, or run `dart pub upgrade --null-safety`.
```

**Comment by sigurdm** [comment]
I like it!

Remember the tests can be updated by deleting the golden files, and rerunning:
```
rm -rf test/outdated/goldens/* ; tool/test.dart
```

**Comment by mit-mit** [comment]
@sigurdm @jonasfj tests are now passing, can you approve?

**Review by jonasfj — APPROVED** [review]

**Pull request merged**
