### PR TITLE
Consider pubspec_overrides.yaml when publishing

### PR DESCRIPTION
**Pull request by sigurdm**
Fix of https://github.com/dart-lang/pub/issues/3781 .

### CODE REVIEW

**Comment by kuhnroyal** [comment]
How can I test this?

**Comment by sigurdm** [comment]
Clone the repo, and [check out the PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally)

Then run `dart <path-to-repo>/bin/pub.dart publish`

**Comment by kuhnroyal** [comment]
Ok this now also gives the cyclic warning but doesn't fail anymore.
The warning references the `pubspec.yaml` file which is missleading.

```
* Your pubspec.yaml is overriding non-dev dependencies.
```

**Comment by sigurdm** [comment]
> The warning references the pubspec.yaml file which is missleading.

Good catch - we could specialize here like we recently did for https://github.com/dart-lang/pub/pull/3684 .

**Comment by sigurdm** [comment]
@jonasfj, when reviewing, consider looking at each commit separately.

The second commit does a rename, because I eventually want to migrate all validation tests to be integration tests.

**Review by jonasfj — APPROVED** [review]

**Comment by jonasfj** [comment]
Thanks for splitting into commits, that made it easy to review all the refactoring :D

**Comment by jakemac53** [comment]
+1 the whole appeal for us is it gives us something like `dependency_overrides` but it only applies to local development and not publishing

**Comment by natebosch** [comment]
> As far as I know the only examples of circular dependencies involve circular dependencies.

I did just introduce a non-dev circular dependency between `test_api` and `matcher`, but I'm going to break the cycle soon. I agree that non-dev dependency cycles are not a use case we need to focus on.

**Comment by sigurdm** [comment]
> As far as I know the only examples of circular dependencies involve circular dependencies.

Haha - perfect mistake :)

**Pull request merged**
