### PR TITLE
Manipulate executable paths only as paths

### LINKED ISSUE #1878: Precompiling executables uses wrong paths on windows
See https://github.com/dart-lang/pub/pull/1871#issuecomment-383813274

### PR DESCRIPTION
**Pull request by natebosch**
Fixes #1878

### CODE REVIEW

**Comment by kevmoo** [comment]
...might consider adding appveyor to the mix for pub – help w/ this?

**Comment by natebosch** [comment]
There seem to be a lot of failing tests on windows outside of this.

I believe this would have been caught, but I don't think we'd get much value out of appveyor without a bunch of work to cleanup the existing tests.

**Comment by kevmoo** [comment]
1) We could always flag the failing tests and exclude them on app veyor
2) It'd be great to understand which tests fail
3) It'd be great to at least make sure the non-failing tests don't start
randomly failing :-)

**Comment by nex3** [comment]
Pub's tests passed on Windows for a long time. The fact that they aren't passing now is as likely to indicate Windows bugs as issues with the tests. It seems like time spent triaging them and ensuring that they all pass would be well-spent.

**Pull request merged**
