### PR TITLE
Use forward slashes in paths when using path dependencies from git dependencies

### PR DESCRIPTION
**Pull request by sigurdm**
Fixes https://github.com/dart-lang/pub/issues/4314

### CODE REVIEW

**Review by jonasfj — APPROVED** [review]

**Comment by CodeDoctorDE** [comment]
is there an option to put this in a hotfix for flutter? I'm really interested having this fixed for my git dependencies

**Comment by sigurdm** [comment]
> is there an option to put this in a hotfix for flutter? I'm really interested having this fixed for my git dependencies

Could you live with a cherry-pick to the dart 3.5/flutter 3.24 beta?

**Comment by CodeDoctorDE** [comment]
It's okay for me, thanks <3

**Comment by sigurdm** [comment]
Ok - I'll first roll this to the sdk - then file a cherry-pick request to beta.

I think we need this https://github.com/dart-lang/pub/pull/4321 to get ci passing...

**Comment by sigurdm** [comment]
This should be in the latest beta now.

**Pull request merged**
