### PR TITLE
Add strict-cast analysis option and fix resulting errors.

### PR DESCRIPTION
**Pull request by bsutton**
analysis option:

  language:
    strict-casts: true

and corrects each of the resulting errors/warnings.
All unit tests are passing except for 4 which I suspect are existing issues.

There is no additional functionality so no new tests have been added.

### CODE REVIEW

**Comment by sigurdm** [comment]
Seems some files need formatting

**Comment by bsutton** [comment]
formatted with dart format.

**Comment by sigurdm** [comment]
I made a PR to your branch with some updates - if you merge that I think we can land this.

**Comment by bsutton** [comment]
Merged the PR as requested.

**Review by sigurdm — APPROVED** [review]

**Comment by sigurdm** [comment]
Big thanks for the contribution!

**Pull request merged**
