### PR TITLE
Produce a better error when Flutter isn't found.

### LINKED ISSUE #1514: running `pub run test` in a flutter project gives unexpected error when missing FLUTTER_ROOT
I was just looking to get `pub run test` options (for other reasons) and didn't realize I was in a flutter project.  The error it gave was not very understandable (and it gave me incorrect directions to file a bug here).

This is not a high priority issue, but we could do a lot better from a UX perspective.  For example, we don't need to error out about missing flutter in the --help case, but more importantly, when we do error out we could give explanations on how to fix it and not direct folks to file a bug. :)

```
pub run test --help                                                                                                [/tmp/foo]
Bad state: Flutter is not available.
package:pub/src/flutter.dart 29       packagePath
package:pub/src/source/sdk.dart 108   BoundSdkSource.getDirectory
package:pub/src/system_cache.dart 97  SystemCache.load
package:pub/src/entrypoint.dart 552   Entrypoint._assertLockFileUpToDate
package:pub/src/entrypoint.dart 484   Entrypoint.assertUpToDate
package:pub/src/entrypoint.dart 105   Entrypoint.packageGraph
package:pub/src/executable.dart 59    runExecutable.<async>
This is an unexpected error. Please run

    pub --trace run test --help

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
```

### PR DESCRIPTION
**Pull request by nex3**
Closes #1514

### CODE REVIEW

**Comment by nex3** [comment]
cc @eseidelGoogle

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
and thanks!

**Comment by eseidelGoogle** [comment]
lgtm2

**Comment by matanlurey** [comment]
@nex3: Am I missing something - I don't see `ApplicationError` defined anywhere.

**Pull request merged**
