### PR TITLE
Update to analyzer `>= 6.2.0`

### PR DESCRIPTION
**Pull request by parlough**

### CODE REVIEW

**Comment by jonasfj** [comment]
@isoos any thoughts?

**Comment by sigurdm** [comment]
I think we should just ship it!

**Comment by isoos** [comment]
lgtm

**Comment by sigurdm** [comment]
Thanks for doing this.

We have dependabot enabled, so we should not need to do this manually. I pushed a button to make dependabot run, and it did the same upgrade. Landing that for a slightly nicer commit message: https://github.com/dart-lang/pub/pull/4019.

**Pull request closed without merging**
