### PR TITLE
Improve formatting of warnings from pub

### LINKED ISSUE #453: Improve formatting of warnings from pub
<a href="https://github.com/sigmundch"></img></a> **Issue by [sigmundch](https://github.com/sigmundch)**
_Originally opened as dart-lang/sdk#8630_

---

We might need some additional line-breaks on the formatting of multiple warnings/errors. In the current form, I visually group the last sentence of a warning with the next warning.

---

Here is an example output today:

Suggestions:
* Your dependency on &quot;browser&quot; should have a version constraint. For example:
&nbsp;&nbsp;
&nbsp;&nbsp;dependencies:
&nbsp;&nbsp;&nbsp;&nbsp;browser: &quot;&gt;=0.3.5+1 &lt;0.3.6&quot;
&nbsp;&nbsp;
&nbsp;&nbsp;Without a constraint, you're promising to support all future versions of browser.
* Your dependency on &quot;args&quot; should have a version constraint. For example:
&nbsp;&nbsp;
&nbsp;&nbsp;dependencies:
&nbsp;&nbsp;&nbsp;&nbsp;args: &quot;&gt;=0.3.5+1 &lt;0.3.6&quot;
&nbsp;&nbsp;
&nbsp;&nbsp;Without a constraint, you're promising to support all future versions of args.
* Your dependency on &quot;logging&quot; should have a version constraint. For example:
&nbsp;&nbsp;
&nbsp;&nbsp;dependencies:
&nbsp;&nbsp;&nbsp;&nbsp;logging: &quot;&gt;=0.3.5+1 &lt;0.3.6&quot;
&nbsp;&nbsp;
&nbsp;&nbsp;Without a constraint, you're promising to support all future versions of logging.
* Your dependency on &quot;js&quot; should have a version constraint. For example:
&nbsp;&nbsp;
&nbsp;&nbsp;dependencies:
&nbsp;&nbsp;&nbsp;&nbsp;js: &quot;&gt;=0.0.16 &lt;0.0.17&quot;
&nbsp;&nbsp;
&nbsp;&nbsp;Without a constraint, you're promising to support all future versions of js.
* Your dependency on &quot;analyzer_experimental&quot; should have a version constraint. For example:
&nbsp;&nbsp;
&nbsp;&nbsp;dependencies:
&nbsp;&nbsp;&nbsp;&nbsp;analyzer_experimental: &quot;&gt;=0.3.5+1 &lt;0.3.6&quot;
&nbsp;&nbsp;
&nbsp;&nbsp;Without a constraint, you're promising to support all future versions of analyzer_experimental.

---

Here is a suggestion for an equivalent warning:

Suggestions:
* Your dependency on &quot;browser&quot; should have a version constraint. For example:
&nbsp;&nbsp;
&nbsp;&nbsp;dependencies:
&nbsp;&nbsp;&nbsp;&nbsp;browser: &quot;&gt;=0.3.5+1 &lt;0.3.6&quot;
&nbsp;&nbsp;
&nbsp;&nbsp;Without a constraint, you're promising to support all future versions of browser.

\* Your dependency on &quot;args&quot; should have a version constraint. For example:
&nbsp;&nbsp;
&nbsp;&nbsp;dependencies:
&nbsp;&nbsp;&nbsp;&nbsp;args: &quot;&gt;=0.3.5+1 &lt;0.3.6&quot;
&nbsp;&nbsp;
&nbsp;&nbsp;Without a constraint, you're promising to support all future versions of args.

\* Your dependency on &quot;logging&quot; should have a version constraint. For example:
&nbsp;&nbsp;
&nbsp;&nbsp;dependencies:
&nbsp;&nbsp;&nbsp;&nbsp;logging: &quot;&gt;=0.3.5+1 &lt;0.3.6&quot;
&nbsp;&nbsp;
&nbsp;&nbsp;Without a constraint, you're promising to support all future versions of logging.

\* Your dependency on &quot;js&quot; should have a version constraint. For example:
&nbsp;&nbsp;
&nbsp;&nbsp;dependencies:
&nbsp;&nbsp;&nbsp;&nbsp;js: &quot;&gt;=0.0.16 &lt;0.0.17&quot;
&nbsp;&nbsp;
&nbsp;&nbsp;Without a constraint, you're promising to support all future versions of js.

\* Your dependency on &quot;analyzer_experimental&quot; should have a version constraint. For example:
&nbsp;&nbsp;
&nbsp;&nbsp;dependencies:
&nbsp;&nbsp;&nbsp;&nbsp;analyzer_experimental: &quot;&gt;=0.3.5+1 &lt;0.3.6&quot;
&nbsp;&nbsp;
&nbsp;&nbsp;Without a constraint, you're promising to support all future versions of analyzer_experimental.

---

Or even collapse similar warnings:

Suggestions:
* Your dependency on &quot;browser&quot;, &quot;args&quot;, &quot;logging&quot;, &quot;js&quot;, and &quot;analyzer_experimental&quot; should have a version constraint. For example:
&nbsp;&nbsp;
&nbsp;&nbsp;dependencies:
&nbsp;&nbsp;&nbsp;&nbsp;browser: &quot;&gt;=0.3.5+1 &lt;0.3.6&quot;
&nbsp;&nbsp;&nbsp;&nbsp;args: &quot;&gt;=0.3.5+1 &lt;0.3.6&quot;
&nbsp;&nbsp;&nbsp;&nbsp;logging: &quot;&gt;=0.3.5+1 &lt;0.3.6&quot;
&nbsp;&nbsp;&nbsp;&nbsp;js: &quot;&gt;=0.0.16 &lt;0.0.17&quot;
&nbsp;&nbsp;&nbsp;&nbsp;analyzer_experimental: &quot;&gt;=0.3.5+1 &lt;0.3.6&quot;
&nbsp;&nbsp;
&nbsp;&nbsp;Without a constraint, you're promising to support all future versions of analyzer_experimental.

### PR DESCRIPTION
**Pull request by AbhishekSatpathy4848**
Improved formatting of warnings from pub by adding an extra new line character. Fix #453

### CODE REVIEW

**Review by sigurdm — CHANGES_REQUESTED** [review]
This won't work in general - we create warnings many places - we need to modify the place where all these are aggregated.

**Review by jonasfj — CHANGES_REQUESTED** [review]
Why do `'...''\n' ?

also unclear why this is needed, I see no test / golden files changes. We need some better indications that this is desired.

**Comment by sigurdm** [comment]
> Why do `'...''\n' ?

The linked original issue asks for better readability when there are several warnings and suggests giving space between them.

**Comment by sigurdm** [comment]
Closing this as inactive.

Feel free to reopen if you want to continue working on this.

**Pull request closed without merging**
