### PR TITLE
fixes: #2670 pub global activate commands always exit cmd on windows.

### PR DESCRIPTION
**Pull request by slightfoot**
Fixes https://github.com/dart-lang/pub/issues/2670

### CODE REVIEW

**Comment by kevmoo** [comment]
@slightfoot – you might want to rebase on master to get travis 🟢

**Comment by slightfoot** [comment]
> @slightfoot – you might want to rebase on master to get travis 🟢

It is on master... 🤔

**Comment by kevmoo** [comment]
...there you go. I landed a fix

**Review by jonasfj — APPROVED** [review]

**Comment by jonasfj** [comment]
Thanks for the fix, this is a nice catch! :D

**Comment by natebosch** [comment]
Can anyone help me understand why this change has the effect of leaving the cmd window open?

**Comment by slightfoot** [comment]
> Can anyone help me understand why this change has the effect of leaving the cmd window open?

I do explain it in the original issue: https://github.com/dart-lang/pub/issues/2670

**Comment by natebosch** [comment]
Ah awesome. That explanation is really clear. Thanks!

**Review by cezaryjk — COMMENTED** [review]
Hi gays,

I'm afraid that this issue is still pending.
I'm on Pub 2.12.0
Executable installation on Windows 10 create batch file with risky GOTO command inside IF block. In some Windows version at least.
"...when GOTO is executed any active FOR/IF command is cancelled and the Batch file continue from the label on. – Aacini ..."
( https://stackoverflow.com/questions/8481558/windows-batch-goto-within-if-block-behaves-very-strangely )

My suggestion is to change batch file structure with something like that:

`@echo off
rem This file was created by pub v2.12.0.
rem Package: fvm
rem Version: 1.3.7
rem Executable: fvm
rem Script: main
if exist "d:\src\flutter.pub-cache\global_packages\fvm\bin\main.dart-2.12.0.snapshot" goto with_snapshot
goto nok_snapshot

:with_snapshot
dart "d:\src\flutter.pub-cache\global_packages\fvm\bin\main.dart-2.12.0.snapshot" %*
rem The VM exits with code 253 if the snapshot version is out-of-date.
rem If it is, we need to delete it and run "pub global" manually.
if not errorlevel 253 goto snapshot_ok
goto nok_snapshot

:nok_snapshot
pub global run fvm:main %*

goto eof

:error
exit /b %errorlevel%

:snapshot_ok

:eof
`
How do you think?
BR
Cezary
[fvmck.bat.txt](https://github.com/dart-lang/pub/files/6129982/fvmck.bat.txt)

(Excuse me if this memo shouldn't be here. I'm not so familiar with Github...)

**Comment by sigurdm** [comment]
@cezaryjk 
Please open as an issue: https://github.com/dart-lang/pub/issues/new

**Comment by cezaryjk** [comment]
Hi Sigurd, 

I’m terrible sorry but it looks like it was false positive. 

The problem was caused by my „complex” environment: I have both Dart and Flutter SDK installed. And yet 1.22.6 and 2.0.1. 
It disappeared after Dart SDK was “promoted” in PATH. 




But still my version of FVM.BAT (attached) works somehow better, giving single course. Probable because launching DART.BAT instead of DART.EXE breaks IF… GOTO commands.   

Thank you very much
Best regards
Cezary

Od: Sigurd Meldgaard
Wysłano: piątek, 12 marca 2021 13:49
Do: dart-lang/pub
DW: Cezary; Mention
Temat: Re: [dart-lang/pub] fixes: #2670 pub global activate commands alwaysexit cmd on windows. (#2671)

@cezaryjk
Please open as an issue: https://github.com/dart-lang/pub/issues/new
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.


@echo off
rem This file was created by pub v2.12.0.
rem Package: fvm
rem Version: 1.3.7
rem Executable: fvm
rem Script: main
if exist "d:\src\flutter\.pub-cache\global_packages\fvm\bin\main.dart-2.12.0.snapshot" goto with_snapshot
goto nok_snapshot

:with_snapshot
  echo Snapshot found
  dart "d:\src\flutter\.pub-cache\global_packages\fvm\bin\main.dart-2.12.0.snapshot" %*
  rem The VM exits with code 253 if the snapshot version is out-of-date.
  rem If it is, we need to delete it and run "pub global" manually.
  echo %errorlevel%
  if not errorlevel 253 goto snapshot_ok 
  goto nok_snapshot

:nok_snapshot
  echo %errorlevel%
  echo Snapshot out-of-date (error 253 caught)
  pub global run fvm:main %*

goto eof

:error
exit /b %errorlevel%

:snapshot_ok
echo Snapshot used (no 253 error caught)

:eof

**Pull request merged**
