### PR TITLE
Use ignore files up to git root

### PR DESCRIPTION
**Pull request by sigurdm**
Fixes: https://github.com/dart-lang/pub/issues/3102

We are still not taking all the same gitignores as git would into account (eg. https://stackoverflow.com/a/5724484) but this is hopefully good enough.

### CODE REVIEW

**Review by jonasfj — APPROVED** [review]

**Comment by jakemac53** [comment]
This caused a global breakage for package:test - since I published from an SDK that included this commit https://github.com/dart-lang/test/issues/1594.

The issue is that we had a `.gitignore` for a file that was actually required for the package (and included in the git repository). It was presumably added to the git repository before the gitignore lines were added.

**Comment by sigurdm** [comment]
We actually validate for files that are .gitignored but checked into git. But  we forgot to update the validator to follow along with this PR.
https://github.com/dart-lang/pub/pull/3169 should fix this.

**Comment by sigurdm** [comment]
I would rather not revert this, as there are issues on the other side of the coin as well (such as #3102).

**Comment by jakemac53** [comment]
That should be sufficient to help avoid this issue - although if we already know those files are checked into git I think we should probably just publish them with the repo instead of warning about them? Or do we have known use cases for that as well?

**Comment by sigurdm** [comment]
>  if we already know those files are checked into git I think we should probably just publish them with the repo instead of warning about them? Or do we have known use cases for that as well

That was part of the reason for implementing .pubignore - sometimes a file should be ignored by git, but published by pub and vice versa.

See issues #2222, #2786, #2566

We implemented it such that a .pubignore in a folder takes precedence over a .gitignore in the same folder. That kind of override would not be possible if we just asked git to evaluate the .gitignores.

I start to think we over engineered this. But I am sure other approaches would have their downsides too.

**Comment by jakemac53** [comment]
It does seem like changing this behavior at this point might be more likely to cause additional problems for people, so I am fine with leaving it as is. If I had gotten the validation warning the issue likely would not have happened, so assuming that goes in it should be good enough.

> That was part of the reason for implementing .pubignore - sometimes a file should be ignored by git, but published by pub and vice versa.

Ya, and we can (and probably will) resolve this in package:test by using `.pubignore`. But it feels like we have the wrong default here to me. I would expect by default my published package to contain all the files that are contained in my git repo - including those that _would be_ covered by the `.gitignore` but were explicitly added.

> See issues #2222, #2786, #2566

I would argue that what https://github.com/dart-lang/pub/issues/2222 is asking for should not be supported. All files published should be committed to the git repo. Otherwise you can't have a tag on git that matches up with what you have published, and there are a ton of foot guns around those files being out of date/missing/etc.

> We implemented it such that a .pubignore in a folder takes precedence over a .gitignore in the same folder. That kind of override would not be possible if we just asked git to evaluate the .gitignores.

This one does get interesting I agree - specifically for https://github.com/dart-lang/pub/issues/2566. I guess maybe I would have taken a layered approach - where you still always only include files committed by git and then the `.pubignore` is only used to exclude additional files. But that only works if you agree with my assertion that we shouldn't publish files that aren't committed to git :).

**Pull request merged**
