### PR TITLE
Support latest analyzer

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by nex3** [comment]
@bwilkerson What were the breaking changes in 0.31.0? The changelog isn't clear on that.

**Comment by kevmoo** [comment]
@nex3 – we rolled everything else through to this version – source_gen, json_serial, angular, dart_style, etc

AFAIK we hit zero breaking issues w/ the APIs – although I also wish they were documented.

...and obviously, pub is shipped against which ever analyzer package is in the SDK when built – which is now beyond even this – just updating as I looked at preview-dart-2 issues running `bin/pub.dart`

**Comment by nex3** [comment]
Presumably there was *some* reason that this had a major version bump, and I'd like to get explicit confirmation that none of the APIs we're using broke in some subtle way.

**Comment by kevmoo** [comment]
There is no documentation about any changes here. We rolled a bunch of packages and they didn't break.

The only place we're not using the latest pkg:analyzer w/ pub is on travis and dev machines 😄

**Comment by nex3** [comment]
Can we get the analyzer team to document the changes, then?

**Comment by kevmoo** [comment]
I doubt it

**Comment by nex3** [comment]
As soon as the changes are documented I'll be happy to roll this forward, but I'm not willing to do it purely based on empirical evidence that nothing else has failed yet. Documenting breaking changes is not a lot to ask—every other package includes a changelog entry for every single release. Telling your users what APIs broke and when is the bare minimum of being a helpful steward of the package ecosystem.

**Comment by kevmoo** [comment]
My concern: we are testing/deving with old angular and are users are
running it with new angular

Changelog or not

On Mar 19, 2018 16:08, "Natalie Weizenbaum" <notifications@github.com>
wrote:

As soon as the changes are documented I'll be happy to roll this forward,
but I'm not willing to do it purely based on empirical evidence that
nothing else has failed yet. Documenting breaking changes is not a lot to
ask—every other package includes a changelog entry for every single
release. Telling your users what APIs broke and when is the bare minimum of
being a helpful steward of the package ecosystem.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dart-lang/pub/pull/1808#issuecomment-374416290>, or mute
the thread

**Comment by nex3** [comment]
> My concern: we are testing/deving with old angular and are users are running it with new angular

I'm not sure what old versus new Angular has to do with anything?

It's clear what needs to happen to get this unblocked, and it's been clear for a month now. It's easy to do. Let's just get the changes documented and get this landed.

**Comment by kevmoo** [comment]
Noone on the analyzer team will take the time to do this now. They are all slammed.

**Pull request closed without merging**
