### PR TITLE
Hide `features` support behind a ENABLE_PUB_FEATURES environment variable

### PR DESCRIPTION
**Pull request by jakemac53**

### CODE REVIEW

**Comment by jakemac53** [comment]
This does have the unfortunate side-effect of making the features related tests fail by default, you have to enable them via the environment variable.

I could add a specific mention of the environment variable but then it also becomes more discoverable which we may not actually want?

**Comment by kevmoo** [comment]
A lot of tests already set up the environment variables before running the client.

Wonder if you should do that instead – otherwise we'll get breaks on the pkg/sdk bots

**Comment by jakemac53** [comment]
@kevmoo these tests don't spawn a subprocess though so I can't set environment variables afaik?

**Comment by kevmoo** [comment]
> these tests don't spawn a subprocess though so I can't set environment variables afaik?

I guess we'd have to get fancy w/ a top-level getter + some other way to override the value

Hrm...

Not a huge deal – but I do worry this will blow up on the pkg/sdk bots

**Comment by jakemac53** [comment]
Added a field which you can override in tests etc, not my favorite but it should get the job done.

**Comment by kevmoo** [comment]
Not perfect, but preferable I think.

**Comment by nex3** [comment]
Can someone provide some context on this?

**Comment by jakemac53** [comment]
We needed to merge pub into the sdk for some other changes but weren't prepared to release the "features" feature for general consumption as we didn't know the status, so we just disabled it for now. If it's ready to release we can go ahead and revert this and merge into the sdk for the next release.

**Comment by nex3** [comment]
Yeah it's good to go! I'll prepare a revert.

**Comment by jakemac53** [comment]
cool, and welcome back!

**Pull request merged**
