### PR TITLE
Follow file symlinks too

### PR DESCRIPTION
**Pull request by lukaslihotzki**
Currently, `pub publish` follows directory symlinks, but not file symlinks. With this PR, file symlinks are followed too. This fixes broken symlinks if they point outside the package root and should not break anything, although it could increase package size.

The dry-run shows the directory tree with directory symlinks resolved, and without indicating symlinks for file symlinks, so it is very confusing currently.

Ideally, symlinks would only be resolved if they point outside the package root. However, that would need two or three tar runs (one with, one without `--dereference`) and using `tar --concatenate` (in the second or the final, third run). It would make the code significantly more complex.

Related issues:
- https://github.com/dart-lang/pub/issues/2193 (Why is this closed?)
- https://github.com/dart-lang/pub/issues/2699

### CODE REVIEW

**Comment by sigurdm** [comment]
I think I agree this is the right behavior.

One issue here is that we don't have the same tar process for windows and linux/macos. On windows we use 7zip. On the other hand symlinks are probably much less used on windows.

Could you write a test that shows this as being fixed?

We are working on migrating to a tar implementation in dart (https://github.com/dart-lang/pub/pull/2817). But it is not clear how long it will take to land. It would be great to have the test for ensuring that the behavior stays consistent when we do the switch.

**Comment by jonasfj** [comment]
> Currently, pub publish follows directory symlinks, but not file symlinks.

It does follow directory symlinks? doesn't it just package the actual symlink?

**Comment by lukaslihotzki** [comment]
> It does follow directory symlinks? doesn't it just package the actual symlink?
It does follow directory symlinks, as shown by the 'publish follows directory symlinks' test in this PR. At least for symlinks pointing to excluded or out-of-package-root targets, this is the only sensible behavior.

**Comment by sigurdm** [comment]
We have merged https://github.com/dart-lang/pub/pull/2817 . If you want we can land the test. I believe our implementation follows links.

**Comment by sigurdm** [comment]
Closing for lack of activity.

Feel welcome to open a new PR with the test if you would like ensuring the desired behavior does not regress.

**Pull request closed without merging**
