### PR TITLE
Use Platform.version even when running from the repo

### PR DESCRIPTION
**Pull request by kevmoo**
Follow-up to https://github.com/dart-lang/pub/commit/3d7ae0cdf0
Hopefully really fixes https://github.com/dart-lang/pub/issues/1887

### CODE REVIEW

**Comment by natebosch** [comment]
Do we not run `pub get` from within the Dart SDK repo anymore?

**Comment by kevmoo** [comment]
I verified this works – I think this will fix the issue where we're not picking up the flutter-flavor of the Dart sdk.

**Comment by natebosch** [comment]
You've tried pulling this in to the Dart SDK and verified the build works?

**Comment by kevmoo** [comment]
Yup. Well, I modified the version of pub in the SDK – and confirmed that
the version is still correct...

**Comment by kevmoo** [comment]
The travis failures were there before – should be investigated

**Pull request merged**
