### PR TITLE
Add "pub run --list" command to show all available executables.

### PR DESCRIPTION
**Pull request by antonmoiseev**
See #1323

### CODE REVIEW

**Comment by nex3** [comment]
See comments [here](https://github.com/dart-lang/pub/issues/1323#issuecomment-230898411).

**Comment by antonmoiseev** [comment]
@nex3 Natalie, I've addressed your comments, I think it's ready for review, please take a look.

**Comment by nex3** [comment]
The more I think about it, the more I feel like this doesn't belong under `pub run`. It does something completely different than running an executable, and none of the existing `pub run` options make sense along with `--list`. I think maybe it would make more sense as an option to `pub deps`, especially since it only prints dependency executables now. Maybe `pub deps --executables`?

**Comment by antonmoiseev** [comment]
I don't have a strong opinion on this one, just some considerations:

1. From organizational point of view `pub deps` looks like a better place
2. I think users will more likely discover it under `pub run`
3. `pub deps` is a more natural place for executables from dependencies, but not sure about executables defined in the current app

Anyway, I'm totally fine with any option you decide is the right thing to do.

**Comment by nex3** [comment]
I agree it's more discoverable under `pub run`, and if it could have subcommands that's what I'd recommend. But that would conflict with running executables, and I don't like making flags do the work of subcommand.

For point 3, `pub deps` already lists the current executable when listing deps, so I don't think it's *too* weird.

**Comment by antonmoiseev** [comment]
OK, moving it to `pub deps`. Should it respect the `--dev` flag?

**Comment by nex3** [comment]
Yeah, it should.

**Comment by nex3** [comment]
@antonmoiseev Are you planning on iterating on this?

**Pull request merged**
