### PR TITLE
Make `pub outdated --json` version info an object

### PR DESCRIPTION
**Pull request by sigurdm**
Fixes: https://github.com/dart-lang/pub/issues/2418

### CODE REVIEW

**Comment by sigurdm** [comment]
cc @kevmoo: you expressed interest in the json format

**Comment by kevmoo** [comment]
Insert gif: "But why?"

What does this help with? How does this improve things?

I already implemented my parser for this. I'm happy to change it, but I don't see the upside here...

**Comment by jonasfj** [comment]
@kevmoo, I think we envision additional meta-data being attached in the future.

Like whether or not a given version is null-safety compatible, reported as broken, or perhaps even reported to have a vulnerability.

By creating the format as an object we can add such properties to each version without breaking existing integrations that rely on the JSON format.

**Comment by kevmoo** [comment]
Totally with you there!

**Pull request merged**
